KP-911 Release v1.2.0
Kaholo/kaholo-plugin-GoogleCloudStorage pull request #10
Opened 2022-08-24 08:50 UTC by xkcm

Added:
* [**KP-596**](https://kaholo.atlassian.net/browse/KP-596) "List Buckets" method

2022-08-24 11:13 UTC, graddaniel submitted a review, later dismissed

2022-08-24 18:06 UTC, kenskyfish requested changes
This one is a disaster - no Accounts, immediately failed, version in config.json wrong, version doesn't belong in package.json, package-lock.json in a release. Did you maybe forget to push your local branch?

Error : Error: Failed to map autocomplete parameters to object – params provided are not an array
at mapAutocompleteFuncParamsToObject (/twiddlebug/libs/plugins/Google-Cloud-Storage/node_modules/@kaholo/plugin-library/autocomplete.js:6:11)

2022-09-06 22:30 UTC, kenskyfish requested changes
Version should be removed from package.json and updated in config.json, right?

2022-09-08 10:55 UTC, xkcm commented
Because of the Accounts feature the new release version should be 2.0.0, not 1.2.0, I will create a new PR.

2022-09-08 10:55 UTC, closed without merging